# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0003_auto_20170328_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeentry.Category')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeentry.Job')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeentry.Task')),
            ],
        ),
    ]
