# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0006_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='crane',
            field=models.BooleanField(default=True),
        ),
    ]
