# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0007_task_crane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='crane',
        ),
    ]
