# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0012_auto_20170506_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeentry.Employer'),
        ),
    ]
