# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0013_auto_20170506_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='employee',
            name='reg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeentry.Employer'),
        ),
    ]
