# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import timeentry.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0014_auto_20170509_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_by', models.CharField(max_length=50)),
                ('entry', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeentry.Category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeentry.DepartmentNum')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeentry.Job')),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True, default=timeentry.models.one_day_hence, null=True),
        ),
    ]
