# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0016_auto_20180112_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proto',
            name='entry',
            field=models.TextField(max_length=1000),
        ),
    ]
