# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import timeentry.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0018_deptcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptcheck',
            name='checkedby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deptcheck',
            name='date',
            field=models.DateField(default=timeentry.models.today),
        ),
    ]
