from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^summary/(?P<job>[0-9]+)$', views.summary, name='summary'),
    url(r'^entrydelete/(?P<pk>[a-zA-z0-9]+)$', views.EntryDelete.as_view(), name='entrydelete'),
    url(r'^clockindelete/(?P<pk>[a-zA-z0-9]+)$', views.ClockInDelete.as_view(), name='clockindelete'),
    url(r'^pto/(?P<year>[0-9]+)/(?P<employee>[0-9]+)$', views.pto, name='pto'),
    url(r'^allpto/(?P<year>[0-9]+)$', views.allpto, name='allpto'),
    url(r'^summary/(?P<job>[0-9]+)/(?P<task>[A-z0-9\-]+)$', views.tasksummary, name='tasksummary'),
    url(r'^summary/', views.selection, name='selection'),
    url(r'^entry/', views.EntryCreate.as_view(success_url='#'), name='entry'), 
    url(r'^clockin/(?P<pk>\d+)/$', views.ClockInUpdate.as_view(), name='clockin-edit',),
    url(r'^clockin/', views.ClockInCreate.as_view(success_url='#'), name='clockin'), 
    url(r'^clockinentry/', views.ClockInCreateManual.as_view(success_url='#'), name='clockin-manual'), 
    url(r'^empentry/', views.EmployeeEntryCreate.as_view(success_url='#'), name='selfentry'), 
    url(r'^proto/(?P<job>[0-9]+)$', views.proto, name='proto'),
    url(r'^proto/', views.protoSelect, name='protoSelect'),
    url(r'^protoEntry/', views.ProtoCreate.as_view(success_url='#'), name='protoCreate'), 
    url(r'^jobEntry/', views.JobCreate.as_view(success_url='#'), name='jobCreate'),   
    url(r'^employeeEntry/', views.EmployeeCreate.as_view(success_url='#'), name='employeeCreate'), 
    url(r'^customerEntry/', views.CustomerCreate.as_view(success_url='#'), name='customerCreate'),   
    url(r'^vms/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)$', views.vms, name='vms'),  
    url(r'^gillman/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)$', views.gillman, name='gillman'),   
    url(r'^aerotek/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)$', views.aerotek, name='aerotek'),   
    url(r'^jobssold/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/(?P<year2>[0-9]+)/(?P<month2>[0-9]+)/(?P<day2>[0-9]+)$', views.jobssold, name='jobssold'),  
    url(r'^vms/', views.vmsselect, name='vmsselect'),
    url(r'^pto/', views.ptoselection, name='ptoselection'),
    url(r'^allpto/', views.allptoselect, name='allptoselect'),
    url(r'^gillman/', views.gillmanselect, name='gillmanselect'),
    url(r'^aerotek/', views.aerotekselect, name='aerotekselect'),
    url(r'^jobssold/', views.jobssoldselect, name='jobssoldselect'),
    url(r'^edit/(?P<pk>\d+)/$', views.EntryUpdate.as_view(), name='entry-edit',),
    url(r'^employee/(?P<pk>\d+)/$', views.EmployeeUpdate.as_view(), name='employee-edit',),
    url(r'^employee/', views.employeeselection, name='employeeselection'),
    url(r'^job/(?P<pk>\d+)/$', views.JobUpdate.as_view(), name='job-edit'),
    url(r'^job/', views.jobselection, name='jobselection'),
    url(r'^protoedit/(?P<pk>\d+)/$', views.ProtoUpdate.as_view(), name='proto-edit',),
    url(r'^timecard/(?P<employee>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)$', views.timecard, name='timecard'),
    url(r'^deptcheck/(?P<department>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)$', views.DeptCheckCreate.as_view(success_url='#'), name='deptcheck'),
    url(r'^deptcheck/', views.deptcheckselect, name='deptcheckselect'),
    url(r'^timecard/', views.timecardselection, name='timecardselection'),
    url(r'^ltsp/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/(?P<year2>[0-9]+)/(?P<month2>[0-9]+)/(?P<day2>[0-9]+)$', views.ltsp, name='ltsp'), 
    url(r'^warranty/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/(?P<year2>[0-9]+)/(?P<month2>[0-9]+)/(?P<day2>[0-9]+)$', views.warranty, name='warranty'), 
    url(r'^empltsp/(?P<employee>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/(?P<year2>[0-9]+)/(?P<month2>[0-9]+)/(?P<day2>[0-9]+)$', views.empltsp, name='empltsp'), 
    url(r'^ltsp/', views.ltspselect, name='ltspselect'),
    url(r'^warranty/', views.warrantyselect, name='warrantyselect'),
    url(r'^worked/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/(?P<year2>[0-9]+)/(?P<month2>[0-9]+)/(?P<day2>[0-9]+)$', views.worked, name='worked'), 
    url(r'^foremenworked/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/(?P<year2>[0-9]+)/(?P<month2>[0-9]+)/(?P<day2>[0-9]+)$', views.foremenworked, name='foremenworked'), 
    url(r'^worked/', views.workedselect, name='workedselect'),
    url(r'^foremenworked/', views.fworkedselect, name='fworkedselect'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]
    